# Generated by Django 2.2.6 on 2019-10-28 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_imageurl_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('collectionid', models.ForeignKey(db_column='collectionid', on_delete=django.db.models.deletion.PROTECT, to='base.Collection')),
            ],
            options={
                'db_table': 'person',
                'managed': True,
                'unique_together': {('name', 'collectionid')},
            },
        ),
        migrations.CreateModel(
            name='Imagepersonannotation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('difficult', models.BooleanField()),
                ('groundtruth', models.BooleanField()),
                ('imageid', models.ForeignKey(db_column='imageid', on_delete=django.db.models.deletion.PROTECT, to='base.Image')),
                ('personid', models.ForeignKey(db_column='personid', on_delete=django.db.models.deletion.PROTECT, to='base.Person')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imagepersonannotation',
                'managed': True,
                'unique_together': {('imageid', 'personid')},
            },
        ),
    ]
